// Bundles only the browser-side nostr-tools signing primitives Kindling needs
// for paste-NSEC login into a single static module served from public/vendor.
//
// public/app.js is served directly to the browser as an ES module, so it cannot
// import the bare "nostr-tools" specifier without a build step. We bundle the
// three primitives the client signer needs — nip19 (decode the nsec), and the
// pure signing helpers getPublicKey + finalizeEvent — into a local file so the
// remote WApp never depends on a third-party script at login time.
//
// Run with: bun scripts/build-nostr-signer.ts

import { rmSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT_FILE = join(ROOT, "public", "vendor", "nostr-signer.js");

// A tiny entry module re-exporting exactly the symbols app.js imports. Pulling
// the signing helpers from nostr-tools/pure keeps relay/websocket code out of
// the bundle. Written to a temp file because this Bun version only bundles from
// real entrypoints, then cleaned up afterwards.
const ENTRY_FILE = join(ROOT, "scripts", ".nostr-signer-entry.ts");
await Bun.write(ENTRY_FILE, [
  'export { nip19 } from "nostr-tools";',
  'export { getPublicKey, finalizeEvent } from "nostr-tools/pure";',
  "",
].join("\n"));

let result;
try {
  result = await Bun.build({
    entrypoints: [ENTRY_FILE],
    target: "browser",
    format: "esm",
    minify: true,
  });
} finally {
  rmSync(ENTRY_FILE, { force: true });
}

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("Failed to bundle nostr-signer");
}

const [artifact] = result.outputs;
if (!artifact) throw new Error("nostr-signer build produced no output");

const banner = "// GENERATED by scripts/build-nostr-signer.ts — do not edit by hand.\n";
await Bun.write(OUT_FILE, banner + (await artifact.text()));
console.log(`Wrote ${OUT_FILE}`);
