#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { Database } from "bun:sqlite";

const TABLES = {
  market_profiles: ["id", "name", "current_version_id", "created_at", "updated_at"],
  market_profile_versions: [
    "id",
    "profile_id",
    "version_number",
    "structured_json",
    "summary",
    "rationale",
    "source_references_json",
    "created_at",
  ],
  service_offerings: [
    "id",
    "market_profile_version_id",
    "key",
    "name",
    "variant_key",
    "structured_json",
    "status",
    "created_at",
    "updated_at",
  ],
  service_fit_assessments: [
    "id",
    "company_id",
    "service_offering_id",
    "market_profile_version_id",
    "score",
    "band",
    "confidence",
    "drivers_json",
    "fit_explanation",
    "evidence_json",
    "caveats_json",
    "recommended_action",
    "source_run_id",
    "assessment_json",
    "created_at",
    "updated_at",
  ],
  target_segments: [
    "id",
    "parent_id",
    "label",
    "tier",
    "priority",
    "status",
    "default_geo",
    "default_target_count",
    "default_batch_size",
    "coverage_targets_json",
    "scan_prompts_json",
    "created_at",
    "updated_at",
  ],
  target_geographies: ["id", "parent_id", "label", "kind", "canonical_key", "status", "created_at", "updated_at"],
  coverage_slices: [
    "id",
    "segment_id",
    "geography_id",
    "geography_text",
    "source_family",
    "strategy_type",
    "status",
    "target_counts_json",
    "current_counts_json",
    "yield_metrics_json",
    "last_run_at",
    "next_run_after_at",
    "stalled_reason",
    "created_at",
    "updated_at",
  ],
  scheduler_settings: [
    "id",
    "enabled",
    "acquisition_enabled",
    "enrichment_enabled",
    "scoring_enabled",
    "outreach_enabled",
    "target_pool_size",
    "enriched_floor",
    "top_target_count",
    "per_role_concurrency_json",
    "cooldowns_json",
    "created_at",
    "updated_at",
  ],
  scheduler_runs: [
    "id",
    "run_type",
    "status",
    "selected_action",
    "skip_reason",
    "role_key",
    "local_request_id",
    "autopilot_run_id",
    "lock_key",
    "context_json",
    "result_json",
    "error",
    "started_at",
    "finished_at",
    "created_at",
    "updated_at",
  ],
  scheduler_locks: ["lock_key", "run_id", "owner_id", "lease_expires_at", "acquired_at", "updated_at"],
  companies: [
    "id",
    "name",
    "location",
    "industry",
    "website",
    "data_ring",
    "duplicate_status",
    "enrichment_status",
    "confidence",
    "profile_json",
    "created_at",
    "updated_at",
  ],
  sources: [
    "id",
    "company_id",
    "source_type",
    "url",
    "title",
    "summary",
    "extracted_data_json",
    "confidence",
    "last_checked_at",
    "last_checked_by_run_id",
    "terms_notes",
    "created_at",
  ],
  customer_profile_versions: [
    "id",
    "company_id",
    "version_number",
    "status",
    "profile_json",
    "change_summary",
    "source_ids_json",
    "activity_ids_json",
    "created_by",
    "created_at",
  ],
  signals: [
    "id",
    "company_id",
    "signal_type",
    "summary",
    "source_id",
    "source_url",
    "observed_date",
    "strength",
    "confidence",
    "adapt_relevance",
    "evidence_json",
    "created_at",
  ],
  activities: ["id", "target_type", "target_id", "actor", "action_type", "summary", "payload_json", "created_at"],
  discovery_jobs: [
    "id",
    "industry",
    "location",
    "segment_id",
    "geography_id",
    "geography_text",
    "coverage_slice_id",
    "target_count",
    "scan_mode",
    "status",
    "company_count",
    "source_count",
    "summary",
    "created_at",
    "updated_at",
  ],
  scan_strategy_attempts: [
    "id",
    "discovery_job_id",
    "segment_id",
    "geography_id",
    "geography_text",
    "coverage_slice_id",
    "source_family",
    "industry",
    "location",
    "strategy_type",
    "query",
    "status",
    "result_count",
    "notes",
    "payload_json",
    "created_at",
  ],
  enrichment_requests: ["id", "company_id", "work_queue_id", "status", "request_kind", "summary", "created_at", "updated_at"],
  work_queue: [
    "id",
    "kind",
    "target_type",
    "target_id",
    "segment_id",
    "segment",
    "priority",
    "status",
    "reason",
    "attempts",
    "next_run_after_at",
    "locked_by_run_id",
    "error",
    "context_json",
    "created_at",
    "updated_at",
  ],
  ranking_runs: [
    "id",
    "ranking_type",
    "status",
    "reason",
    "candidate_count",
    "ranked_count",
    "score_version",
    "parameters_json",
    "created_by",
    "started_at",
    "completed_at",
    "created_at",
    "updated_at",
  ],
  ranking_items: ["id", "ranking_run_id", "company_id", "rank", "score", "reason", "score_json", "created_at"],
  target_list_runs: [
    "id",
    "status",
    "reason",
    "candidate_count",
    "ranked_count",
    "score_version",
    "parameters_json",
    "created_by",
    "started_at",
    "completed_at",
    "created_at",
    "updated_at",
  ],
  target_list_items: [
    "id",
    "target_list_run_id",
    "company_id",
    "service_fit_assessment_id",
    "market_profile_version_id",
    "rank",
    "score",
    "reason",
    "best_offering_id",
    "best_offering_key",
    "best_offering_name",
    "best_variant_key",
    "why_now",
    "evidence_quality",
    "confidence",
    "caveats_json",
    "next_action",
    "flags_json",
    "score_json",
    "created_at",
  ],
  outreach_drafts: ["id", "company_id", "pitch_text", "status", "source_run_id", "created_at", "updated_at"],
  company_segments: ["company_id", "segment_id", "confidence", "source", "created_at"],
} as const;

function argValue(name: string, fallback: string) {
  const index = Bun.argv.indexOf(name);
  return index >= 0 ? Bun.argv[index + 1] ?? fallback : fallback;
}

const dbPath = argValue("--db", process.env.CHAT_WAPP_DB_PATH || "data/chat-wapp.sqlite");
const outputPath = resolve(argValue("--out", `data/kindling-export-${new Date().toISOString().replace(/[:.]/g, "-")}.json`));
const db = new Database(dbPath, { readonly: true });
const tables: Record<string, unknown[]> = {};
const counts: Record<string, number> = {};

for (const [table, columns] of Object.entries(TABLES)) {
  const rows = db.query(`SELECT ${columns.join(", ")} FROM ${table}`).all() as Record<string, unknown>[];
  tables[table] = rows;
  counts[table] = rows.length;
}

const payload = {
  exportedAt: new Date().toISOString(),
  source: {
    dbPath,
    app: "kindling",
  },
  counts,
  tables,
};

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${JSON.stringify(payload)}\n`, "utf8");
console.log(JSON.stringify({ outputPath, counts }, null, 2));
